import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faPhone,
    faUser,
    faFlag,
    faDashboard,
    faArrowUp,
    faUsers,
    faTrash,
    faBan,
    faPaperclip,
    faUserGroup,
    faChevronDown,
    faAnglesDown,
    faEnvelope,
    faCog,
    faEdit,
    faFileImport,
    faFileLines,
    faBookBookmark,
    faPlus,
    faFaceSmile,
    faWarehouse,
    faRuler,
    faBasketShopping,
    faDollarSign,
    faHandHoldingDollar,
    faMinus,
    faHandshakeSimple,
    faCheck,
    faCartFlatbed,
    faPhotoFilm
    
} from "@fortawesome/free-solid-svg-icons";

library.add(
    faPhone,
    faUser,
    faFlag,
    faDashboard,
    faArrowUp,
    faUsers,
    faTrash,
    faBan,
    faPaperclip,
    faUserGroup,
    faChevronDown,
    faAnglesDown,
    faEnvelope,
    faCog,
    faEdit,
    faFileImport,
    faFileLines,
    faBookBookmark,
    faPlus,
    faFaceSmile,
    faWarehouse,
    faRuler,
    faBasketShopping,
    faDollarSign,
    faHandHoldingDollar,
    faMinus,
    faHandshakeSimple,
    faCheck,
    faCartFlatbed,
    faPhotoFilm
);

export default FontAwesomeIcon;
